//Error constants

module.exports = {
  CORS_ORIGIN: "CORS_ORIGIN",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  DB_CONNECTION_FAILED: "DB_CONNECTION_FAILED",
  DB_ERROR: "DB_ERROR",
};
